Report and crash when error is found
Errors print out the line/column and surrounding lines where the error
occured.

k :: X -> Y
k x = Y{x}.

Would generate the error:

33| k :: X -> Y
34| k x = Y{x}.
  | ~~~~~~~~^
35|
Error: Trying to store argument pointer into a local struct

because storing argument pointers into a local struct is illegal
(since it can cause use after free errors).

Signed-off-by: Jadon Fowler <jadonflower@gmail.com>